name: Go CI/CD

on:
  push:
    branches:
      - 'master'
      - 'lab*'
    paths:
      - 'app_go/**'
      - '.github/workflows/go-ci.yml'
  pull_request:
    branches: [ 'master' ]
    paths:
      - 'app_go/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: 'app_go/go.sum'

      - name: Install dependencies
        working-directory: app_go
        run: go mod download

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Scan  with Snyk Code
        working-directory: app_go
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: 
          snyk config set api=$SNYK_TOKEN
          snyk code test . --severity-threshold=high
          snyk test --file=go.mod --package-manager=gomodules --severity-threshold=high

      - name: Lint Go code
        working-directory: app_go
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Run tests with coverage
        working-directory: app_go
        run: |
          go test -v -coverprofile=coverage.out -covermode=atomic ./...
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage to Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          working-directory: app_go 
          path-to-profile: coverage.out
          parallel: true
          flag-name: go-unit-tests

  docker:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Generate CalVer version 
        id: calver
        run: |
          YEAR_MONTH=$(date +'%Y.%m')
          VERSION="${YEAR_MONTH}.${{ github.run_number }}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "year_month=${YEAR_MONTH}" >> $GITHUB_OUTPUT
          echo "Generated CalVer: ${VERSION}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app_go
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/devops-info-service-go:latest
            ${{ secrets.DOCKER_USERNAME }}/devops-info-service-go:${{ steps.calver.outputs.version }}