name: Python CI/CD

on:
  push:
    branches:
      - 'master'
      - 'lab*'
    paths:
      - 'app_python/**'
      - '.github/workflows/python-ci.yml'
  pull_request:
    branches: [ 'master' ]
    paths:
      - 'app_python/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: app_python/requirements*.txt

      - name: Install dependencies
        working-directory: app_python
        run: |
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          else
            pip install pytest flake8 pytest-cov
          fi

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Scan ONLY app.py with Snyk Code
        working-directory: app_python
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: 
          snyk config set api=$SNYK_TOKEN
          snyk code test . --severity-threshold=high

      - name: Lint
        working-directory: app_python
        run: flake8 app.py

      - name: Test
        working-directory: app_python
        run: pytest tests/

      - name: Run tests with coverage
        working-directory: app_python
        run: |
          pytest tests/ --cov=. --cov-report=xml --cov-report=term --cov-fail-under=70

      - name: Upload coverage to Coveralls
        working-directory: app_python
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github

  docker:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Generate CalVer version 
        id: calver
        run: |
          YEAR_MONTH=$(date +'%Y.%m')
          VERSION="${YEAR_MONTH}.${{ github.run_number }}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "year_month=${YEAR_MONTH}" >> $GITHUB_OUTPUT
          echo "Generated CalVer: ${VERSION}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app_python
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/devops-info-service:latest
            ${{ secrets.DOCKER_USERNAME }}/devops-info-service:${{ steps.calver.outputs.version }}